EXERCISE_CONFIG = {
    "display_name": "Push-up",
    "mode": "reps",
    "view": "side",
    "initial_stage": "up",
    "side_check": "elbow",
    "set_size": 8,
    "rest_seconds": 20,
    "calibrate_seconds": 2.5,
    "setup_hint": "Turn sideways. For best 3D measurement, angle slightly (45-deg) so both arms are visible.",
    "important_joints": ["shoulder", "elbow", "wrist"],
    "calibrate_hint": "Hold the top of a push-up with arms straight",
    "not_visible_message": "Body not clearly visible - turn sideways to the camera",
    "landmarks": {
        "left": {
            "ear": 7, "shoulder": 11, "elbow": 13, "wrist": 15,
            "hip": 23, "knee": 25, "ankle": 27,
        },
        "right": {
            "ear": 8, "shoulder": 12, "elbow": 14, "wrist": 16,
            "hip": 24, "knee": 26, "ankle": 28,
        },
    },
    "checks": {
        "elbow": {
            "type": "angle",
            "points": ("shoulder", "elbow", "wrist"),
            "down_threshold": 130,
            "up_threshold": 160,
        },
        "elbow_depth": {
            "type": "angle",
            "points": ("shoulder", "elbow", "wrist"),
            "down_threshold": 90,
            "up_threshold": None,
        },
        "body_line": {
            "type": "angle",
            "points": ("shoulder", "hip", "ankle"),
            "down_threshold": 155,
            "up_threshold": None,
            "direction": "below",
        },
        "hip_sag": {
            "type": "signed_line_offset",
            "points": ("shoulder", "hip", "ankle"),
            "down_threshold": 0.08,
            "up_threshold": None,
            "direction": "above",
        },
        "hip_pike": {
            "type": "signed_line_offset",
            "points": ("shoulder", "hip", "ankle"),
            "down_threshold": -0.08,
            "up_threshold": None,
            "direction": "below",
        },
        "knee": {
            "type": "angle",
            "points": ("hip", "knee", "ankle"),
            "down_threshold": 150,
            "up_threshold": None,
            "direction": "below",
        },
        "elbow_flare": {
            "type": "angle",
            "points": ("hip", "shoulder", "elbow"),
            "down_threshold": 125,
            "up_threshold": None,
            "direction": "above",
        },
        "head_drop": {
            "type": "signed_line_offset",
            "points": ("hip", "ear", "shoulder"),
            "down_threshold": 0.12,
            "up_threshold": None,
            "direction": "above",
        },
    },
    "primary_check": "elbow",
    "depth_checks": ["elbow_depth"],
    "fault_checks": ["hip_sag", "hip_pike", "knee", "body_line", "elbow_flare", "head_drop"],
    "feedback_rules": [
        {
            "require": {
                "elbow_depth": True,
                "hip_sag": False, "hip_pike": False, "knee": False,
                "body_line": False, "elbow_flare": False, "head_drop": False,
            },
            "message": "Rep {count}: Clean push-up!",
            "counts_as_good": True,
        },
        {
            "require": {"hip_sag": True},
            "message": "Rep {count}: Hips sagging - brace your core",
            "counts_as_good": False,
        },
        {
            "require": {"hip_pike": True},
            "message": "Rep {count}: Hips too high - keep a straight plank line",
            "counts_as_good": False,
        },
        {
            "require": {"elbow_flare": True},
            "message": "Rep {count}: Elbows flaring - tuck them closer to your ribs",
            "counts_as_good": False,
        },
        {
            "require": {"head_drop": True},
            "message": "Rep {count}: Head dropping - look slightly ahead, not down",
            "counts_as_good": False,
        },
        {
            "require": {"knee": True},
            "message": "Rep {count}: Knees dropping - keep legs straight",
            "counts_as_good": False,
        },
        {
            "require": {"body_line": True},
            "message": "Rep {count}: Body broke line - stay rigid from head to heels",
            "counts_as_good": False,
        },
        {
            "require": {"elbow_depth": False},
            "message": "Rep {count}: Not deep enough - lower your chest",
            "counts_as_good": False,
        },
    ],
    "default_message": "Rep {count}: Not deep enough - lower your chest",
}
