services:
  - type: web
    name: fitpath-ai-backend
    runtime: docker
    plan: free
    region: oregon
    dockerfilePath: ./Dockerfile
    envVars:
      - key: PORT
        value: 8000
      - key: PYTHONUNBUFFERED
        value: "1"
