EXERCISE_CONFIG = {
    "display_name": "Dead Bug",
    "mode": "hold",
    "view": "side",
    "initial_stage": "rest",
    "hold_direction": "above",
    "side_check": "knee",
    "calibrate_seconds": 2.5,
    "setup_hint": "Lie on your back, sideways to the camera. For best 3D measurement, angle slightly.",
    "important_joints": ["shoulder", "elbow", "wrist", "hip", "knee", "ankle"],
    "calibrate_hint": "Extend one leg and the opposite arm without arching",
    "not_visible_message": "Lie on your back, camera from the side",
    "landmarks": {
        "left": {
            "shoulder": 11, "elbow": 13, "wrist": 15,
            "hip": 23, "knee": 25, "ankle": 27,
        },
        "right": {
            "shoulder": 12, "elbow": 14, "wrist": 16,
            "hip": 24, "knee": 26, "ankle": 28,
        },
    },
    "checks": {
        "knee": {
            "type": "max_angle",
            "points": ("hip", "knee", "ankle"),
            "down_threshold": 140,
            "up_threshold": 155,
            "direction": "above",
        },
        "torso_flat": {
            "type": "vertical_angle",
            "points": ("shoulder", "hip"),
            "down_threshold": 75,
            "up_threshold": None,
            "direction": "above",
        },
        "leg_extended": {
            "type": "max_angle",
            "points": ("shoulder", "hip", "ankle"),
            "down_threshold": 145,
            "up_threshold": None,
            "direction": "above",
        },
        "leg_tabletop": {
            "type": "min_angle",
            "points": ("shoulder", "hip", "knee"),
            "down_threshold": 115,
            "up_threshold": None,
            "direction": "below",
        },
        "arm_extended": {
            "type": "max_angle",
            "points": ("hip", "shoulder", "wrist"),
            "down_threshold": 145,
            "up_threshold": None,
            "direction": "above",
        },
        "arm_up": {
            "type": "min_angle",
            "points": ("hip", "shoulder", "wrist"),
            "down_threshold": 115,
            "up_threshold": None,
            "direction": "below",
        },
        "low_back_arch": {
            "type": "signed_line_offset",
            "points": ("shoulder", "hip", "knee"),
            "down_threshold": -0.14,
            "up_threshold": None,
            "direction": "below",
        },
    },
    "primary_check": "knee",
    "depth_checks": ["knee", "torso_flat", "leg_extended", "leg_tabletop", "arm_extended", "arm_up"],
    "fault_checks": ["low_back_arch"],
    "feedback_rules": [
        {
            "require": {"knee": True, "torso_flat": True, "leg_extended": True, "leg_tabletop": True, "arm_extended": True, "arm_up": True, "low_back_arch": False},
            "message": "Ribs down, {side} leg reaching long",
            "counts_as_good": True,
        },
        {
            "require": {"low_back_arch": True},
            "message": "Low back arching - press your ribs toward the floor",
            "counts_as_good": False,
        },
        {
            "require": {"torso_flat": False},
            "message": "Keep your back on the floor - don't sit up",
            "counts_as_good": False,
        },
        {
            "require": {"leg_extended": False},
            "message": "Extend your leg straight out, parallel to the floor",
            "counts_as_good": False,
        },
        {
            "require": {"leg_tabletop": False},
            "message": "Keep your resting leg bent at 90 degrees",
            "counts_as_good": False,
        },
        {
            "require": {"arm_extended": False},
            "message": "Extend the opposite arm straight back towards the floor",
            "counts_as_good": False,
        },
        {
            "require": {"arm_up": False},
            "message": "Keep your resting arm pointing straight up to the ceiling",
            "counts_as_good": False,
        },
        {
            "require": {"knee": False},
            "message": "Extend one leg toward the floor, slow and controlled",
            "counts_as_good": False,
        },
    ],
    "default_message": "Extend opposite arm and leg without arching",
}
